CREATE TABLE insert_type (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    name_kg VARCHAR(200),
    code VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    description_kg TEXT,
    handler_type VARCHAR(20) NOT NULL DEFAULT 'local',
    handler_class VARCHAR(200),
    handler_endpoint VARCHAR(500),
    handler_method VARCHAR(10) DEFAULT 'POST',
    requires_auth BOOLEAN DEFAULT FALSE,
    auth_type VARCHAR(50),
    auth_credentials TEXT,
    timeout_seconds INTEGER DEFAULT 30,
    max_retries INTEGER DEFAULT 3,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by INTEGER,
    updated_by INTEGER,
    deleted_at TIMESTAMP,
);