-- Таблица application
CREATE TABLE application (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_date    TIMESTAMP,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    created_by           INTEGER,
    updated_by           INTEGER,
    deadline             TIMESTAMP,
    number               TEXT,
    comment              TEXT,
    work_description     TEXT,
    status_id            INTEGER,
    company_id           INTEGER NOT NULL,
    r_service_id         INTEGER,
    r_service_name       TEXT,
    unique_code          TEXT,
    app_cabinet_uuid     TEXT,
    reject_html          TEXT
);

-- Таблица application_paid_invoice
CREATE TABLE application_paid_invoice (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       INTEGER,
    customer_id          INTEGER,
    date                 TIMESTAMP,
    payment_identifier   TEXT,
    sum                  DOUBLE PRECISION,
    description          TEXT,
    additional           TEXT
);

-- Таблица customer
CREATE TABLE customer (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    created_by           INTEGER,
    updated_by           INTEGER,
    name                 TEXT,
    address              TEXT,
    director             TEXT,
    nomer                TEXT,
    pin                  TEXT,
    okpo                 TEXT,
    postal_code          TEXT,
    ugn                  TEXT,
    reg_number           TEXT,
    organization_type_id INTEGER,
    foreign_country      INTEGER,
    is_foreign           BOOLEAN
);

-- Внешние ключи
ALTER TABLE application
    ADD CONSTRAINT fk_application_status 
    FOREIGN KEY (status_id) 
    REFERENCES application_status(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE application
    ADD CONSTRAINT fk_company 
    FOREIGN KEY (company_id) 
    REFERENCES customer(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE application_paid_invoice
    ADD CONSTRAINT fk_invoice_application 
    FOREIGN KEY (application_id) 
    REFERENCES application(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE application_paid_invoice
    ADD CONSTRAINT fk_invoice_customer 
    FOREIGN KEY (customer_id) 
    REFERENCES customer(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE customer
    ADD CONSTRAINT fk_organization_type 
    FOREIGN KEY (organization_type_id) 
    REFERENCES organization_type(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;